name: Go
on: [push]
jobs:

  build:
    name: Build
    runs-on: ubuntu-latest
    steps:

    - name: Set up Go 1.12
      uses: actions/setup-go@v1
      with:
        go-version: 1.12
      id: go

    - name: Check out code into the Go module directory
      uses: actions/checkout@v1

    - name: Fix GOPATH
      # temporary fix
      # see https://github.com/actions/setup-go/issues/12
      # see https://github.com/actions/setup-go/issues/14
      run: |
        export GOPATH=$HOME/go
        export GOBIN=$(go env GOPATH)/bin
        echo $GOPATH
        echo $GOBIN
        export PATH=$PATH:$GOPATH
        export PATH=$PATH:$GOBIN
        mkdir -p $GOPATH/pkg
        mkdir -p $GOBIN
        mkdir -p $GOPATH/src/github.com/$GITHUB_REPOSITORY
        mv $(pwd)/* $GOPATH/src/github.com/$GITHUB_REPOSITORY
        echo "::set-env name=REPOPATH::$GOPATH/src/github.com/$GITHUB_REPOSITORY"
        echo "::set-env name=GOPATH::$GOPATH"
        echo "::set-env name=GOBIN::$GOBIN"

    - name: Install packages
      run: |
        export PATH=$PATH:$GOPATH
        export PATH=$PATH:$GOBIN
        curl https://glide.sh/get | sh

    - name: Get dependencies
      run: |
        cd $REPOPATH
        $GOPATH/bin/glide -v
        $GOPATH/bin/glide update
#         go get -v -t -d ./...
#         if [ -f Gopkg.toml ]; then
#             curl https://raw.githubusercontent.com/golang/dep/master/install.sh | sh
#             dep ensure
#         fi

    - name: Test
      run: |
        pwd && ls
        cd $REPOPATH
        ./test.sh

    - name: Build
      run: |
        cd $REPOPATH
        go build -v .

    
