name: Release
on:
  release:
    types: [released]
env:
  PERSONAL_ACCESS_TOKEN: ${{ secrets.PERSONAL_ACCESS_TOKEN }} 

jobs:

  build:
    name: Build
    runs-on: ubuntu-latest
    steps:

    - name: Check out code into the Go module directory
      uses: actions/checkout@v2

    - name: Release
      run: |
        cd $REPOPATH
        echo "release"

        curl -v -X POST \
          -H "Authorization: Bearer ${PERSONAL_ACCESS_TOKEN}" \
          -H "Accept: application/vnd.github.v3+json" \
          https://api.github.com/repos/sunao-uehara/go-github-actions/dispatches \
          -d '{"event_type":"deploy"}'