name: Release
on:
  release:
    types: [released]
env:
  PERSONAL_ACCESS_TOKEN: ${{ secrets.PERSONAL_ACCESS_TOKEN }} 

jobs:

  build:
    name: Release
    runs-on: ubuntu-latest
    steps:

    - name: Check out code
      uses: actions/checkout@v2
      with:
        fetch-depth: '2'
    - run: git checkout HEAD^ 

    - name: Prerequisites
      run: |
        git version

    - name: Release
      run: |
        # cd $REPOPATH
        pwd
        commit_message=$(git log -1 --pretty=format:"%s")

        echo ${{ github.actor }}
        echo ${{ github.sha }}
        echo "$commit_message"

        echo $GITHUB_REPOSITORY
        echo $GITHUB_ACTOR
        echo $GITHUB_REF
        echo $GITHUB_REF_NAME

        curl -v -X POST \
          -H "Authorization: Bearer ${PERSONAL_ACCESS_TOKEN}" \
          -H "Accept: application/vnd.github.v3+json" \
          https://api.github.com/repos/sunao-uehara/go-github-actions/dispatches \
          -d '{
            "event_type":"deploy"
            "client_payload": {
              "repository": "${GITHUB_REPOSITORY}",
              "path": "/abc/def/resouce.yaml",
              "version": "${GITHUB_REF_NAME}",
              "image": "test-${GITHUB_REF_NAME}",
              "author": "${GITHUB_ACTOR}",
              "sha": "${GITHUB_ACTOR}",
              "message": "${commit_message}"
            }
          }'