name: respository_dispatch test
on:
  repository_dispatch:
    # types: [test, build, deploy]

jobs:

  build:
    name: Build
    runs-on: ubuntu-latest
    steps:

    - name: Check out code into the Go module directory
      uses: actions/checkout@v2

    - name: Test
      run: |
        cd $REPOPATH
        echo "test"

    - name: Build
      run: |
        cd $REPOPATH
        echo "build"
    
    - name: Deploy
      run: |
        cd $REPOPATH
        echo "deploy"
