name: respository_dispatch test
on:
  repository_dispatch:
    types: [test, build, deploy]

jobs:
  build:
    name: Deploy
    runs-on: ubuntu-latest
    steps:

    - name: Check out code into the Go module directory
      uses: actions/checkout@v2
    
    - name: Step 1
      run: |
        cd $REPOPATH
        echo "deploy"
        echo ${{ github.event.client_payload.repository }}
        echo "payload: ${{ toJson(github.event.client_payload) }}"

